# ============================================================
# Adversarial Training Objective (Min–Max Game)
# ============================================================
#
# We are training two models in opposition:
#
# 1. Forecast Model (f_θ):
#    This model tries to minimize prediction error (MSE)
#    on data generated by the generator.
#
#    Objective:
#        θ* = argmin_θ MSE(f_θ(G(z)), y)
#
#    Meaning:
#    - Given generator-produced data G(z)
#    - The forecast model learns to predict y accurately
#
#
# 2. Generator Model (G_φ):
#    This model tries to make the forecast model perform worse.
#    It learns to generate data that maximizes prediction error.
#
#    Objective:
#        φ* = argmax_φ MSE(f_θ(G_φ(z)), y)
#
#    Meaning:
#    - Generator modifies data distribution G_φ(z)
#    - It tries to fool the forecast model into making errors
#
#
# ============================================================
# Overall Game:
# ============================================================
#
# min-max optimization:
#
#     min_θ max_φ  MSE(f_θ(G_φ(z)), y)
#
# This creates an adversarial loop where:
# - Forecast model improves prediction ability
# - Generator continuously tries to make prediction harder
#
# ============================================================


from data_generator.x_feature_registery import XFeatureRegistery
from data_generator.generator_model import GeneratorModel
from dataset.dataset_builder import DatasetBuilder
from dataset.equence_builder import SequenceBuilder
from dataset.normalizer import DataNormalizer
from dataset.splitter import TimeSeriesSplitter
from training.generator_trainer import GeneratorTrainer
from training.forcast_trainer import ForcasterTrainer
from core.config import Config
import torch
from forcast_model.grid_search import GridSearchEngine
from training.pipline_tracker import PipelineTracker



class BasePipeline:
    def __init__(
        self,
        name: str,
        x_registery: XFeatureRegistery,
        gen_model: GeneratorModel,
        grid_search_engine: GridSearchEngine,
    ):
        self.config = Config()
        self.tracker = PipelineTracker()
        self.normalizer = DataNormalizer()
        self.splitter = TimeSeriesSplitter()
        self.dataset_builder = DatasetBuilder()
        self.gen_trainer = GeneratorTrainer(gen_model)
        self.sequence_builder = SequenceBuilder(
            seq_len=self.config.seq_len,
            pred_len=self.config.pred_len,
        )
        self.grid_search_engine = grid_search_engine
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.name = name
        self.x_registery = x_registery
        self.gen_model = gen_model
        self.forcast_trainer = None

    def select_best_model(
        self,
        X_train: torch.Tensor,
        Y_train: torch.Tensor,
        X_test: torch.Tensor,
        Y_test: torch.Tensor,
    ):
        best_model, best_score, best_params, grid_df = self.grid_search_engine.search(
            X_train,
            Y_train,
            X_test,
            Y_test,
        )
        self.forcast_trainer = ForcasterTrainer(best_model)
        self.tracker.log_grid_search(
            grid_df=grid_df,
            best_params=best_params,
            best_score=best_score,
        )
        return best_model, best_score
    
    def predict(self, X: torch.Tensor)-> torch.Tensor:
        preds = self.forcast_trainer.forward(X)
        return preds.squeeze(-1)

    def _compute_mse(self, X: torch.Tensor, Y: torch.Tensor) -> torch.Tensor:
        preds = self.predict(X)
        Y = Y.squeeze(-1)
        return torch.mean((preds - Y) ** 2)

    def run_step(self, epoch_num: int):
        # =========================
        # 1. GENERATE DATA (ONLY ONCE)
        # =========================
        X_raw, Y_raw = self.dataset_builder.build(
            self.x_registery,
            self.gen_model,
            n_samples=self.config.total_samples
        )

        # =========================
        # 2. NORMALIZE
        # =========================
        self.normalizer.fit(X_raw, Y_raw)
        X, Y = self.normalizer.transform(X_raw, Y_raw)

        # =========================
        # 3. SEQUENCE BUILD
        # =========================
        X_seq, Y_seq = self.sequence_builder.build(X, Y)

        # =========================
        # 4. SPLIT
        # =========================
        X_train, Y_train, X_test, Y_test = self.splitter.split(X_seq, Y_seq)

        X_train, Y_train = X_train.to(self.device), Y_train.to(self.device)
        X_test, Y_test = X_test.to(self.device), Y_test.to(self.device)
        
        # =========================
        # 5. TRAIN MODEL (multiple epochs like original)
        # =========================
        model_loss = self.forcast_trainer.train(X_train, Y_train.detach())
        self.forcast_trainer.model.eval_mode()
        # =========================
        # 6. FREEZE MODEL
        # =========================
        self.forcast_trainer.model.freeze()

        # =====================================================
        # 7. TRAIN GENERATOR (ADVERSARIAL LOOP)
        # =====================================================
        for _ in range(self.config.generator_epoch):

            with torch.no_grad():
                preds = self.forcast_trainer.forward(X_train)

                loss_g = self.forcast_trainer.criterion(preds, Y_train)
                    
            # generator maximizes model error
            # preds = self.forcast_trainer.forward(X_train)

            # loss_g = self.forcast_trainer.criterion(preds, Y_train)

            # self.gen_trainer.optimizer.zero_grad()

            # (-loss_g).backward()

            self.gen_trainer.step(loss_g)

        # =========================
        # 8. UNFREEZE MODEL
        # =========================
        self.forcast_trainer.model.unfreeze()
        
        # =========================
        # 9. EVALUATION
        # =========================
        test_loss = self._compute_mse(X_test, Y_test)
        
        # =========================
        # 10. TRACK
        # =========================
        self.tracker.log_step(
            step=epoch_num,
            model_loss=float(model_loss.item()),
            generator_loss=float(test_loss.item()),
            gen_model=self.gen_model,
            X_raw=X_raw,
            Y_raw=Y_raw,
            predictions=preds,
            targets=Y_test.detach().cpu(),
        )
        print(f"Epoch {epoch_num}: model_loss={model_loss.item():.4f}, generator_loss={test_loss.item():.4f}")

    def run(self):

        # STEP 1: generate dataset ONCE for grid search
        X_raw, Y_raw = self.dataset_builder.build(
            self.x_registery,
            self.gen_model,
            n_samples=self.config.total_samples,
        )

        # 2. Normalize (optional but recommended)
        self.normalizer.fit(X_raw, Y_raw)
        X, Y = self.normalizer.transform(X_raw, Y_raw)

        # 3. Convert to sequences
        X_seq, Y_seq = self.sequence_builder.build(X, Y)

        # 4. Split
        X_train, Y_train, X_test, Y_test = self.splitter.split(X_seq, Y_seq)

        X_train, Y_train = X_train.to(self.device), Y_train.to(self.device)
        X_test, Y_test = X_test.to(self.device), Y_test.to(self.device)

        # 5. find best model
        self.select_best_model(X_train, Y_train, X_test, Y_test)

        # 6. adversarial training loop
        return [self.run_step(epoch_num=epoch) for epoch in range(self.config.training_epochs)]
